[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
conduit-mime-types = "0.8.0"
cmtm = { package= "conduit-mime-types", path = ".." }
xxh3 = "0.1.1"
